safe:       true
markdown:   redcarpet
highlighter: rouge
name: "Dash to Dock GNOME Shell extension"
description: "A dock for the GNOME Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and workspaces."
url: "https://micheleg.github.io/dash-to-dock"
paginate: 5
paginate_path: "news/page:num"
excerpt_separator: <!--more-->
extension_page_url: "https://extensions.gnome.org/extension/307/dash-to-dock"
github_project_url: "https://github.com/micheleg/dash-to-dock"
release_page_url: "/releases.html"
